export const eventCategories = [
  "Boliches",
  "Capacitaciones",
  "Conciertos",
  "Cursos y talleres",
  "Eventos corporativos",
  "Eventos culturales",
  "Eventos de autos",
  "Eventos de belleza",
  "Eventos de bienes raíces",
  "Eventos de caridad",
  "Eventos de ciencia y tecnología",
  "Eventos de crecimiento personal",
  "Eventos de marketing y publicidad",
  "Eventos de motos",
  "Eventos de salud",
  "Eventos deportivos",
  "Eventos digitales",
  "Eventos fin de año",
  "Eventos gastronómicos",
  "Eventos internacionales",
  "Eventos musicales",
  "Eventos para emprendedores",
  "Eventos políticos",
  "Eventos religiosos",
  "Ferias presenciales",
  "Ferias y expos",
  "Juegos y juguetes",
  "Networkings",
  "Ruedas de negocios",
  "Webinars"
];
